lifycycle:
  interval: 1m
# Paths to files you want to backup
files:
  - path:
# Path to save the backup
output:
  file:
    enabled: true
    path:
  email:
    addr: smtp.gmail.com
    to_addr:
    subj: Backup
    username:
    api_key:
    timeout: 30s